name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ["6.1"]
    container:
      image: swift:${{ matrix.swift-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build package
        run: swift build --verbose

      - name: Run tests
        run: swift test --verbose

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        swift-version: ["6.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build package
        run: swift build --verbose

      - name: Run tests
        run: swift test --verbose
